INSERT INTO `region` VALUES (43, '244', '安哥拉', '安哥拉', 'AO', 'Angola', '-7', 1, 1, 'アンゴラ');
INSERT INTO `region` VALUES (44, '93', '阿富汗', '阿富汗', 'AF', 'Afghanistan', '0', 1, 1, 'アフガニスタン');
INSERT INTO `region` VALUES (45, '355', '阿爾巴尼亞', '阿尔巴尼亚', 'AL', 'Albania', '-7', 1, 1, 'アルバニア');
INSERT INTO `region` VALUES (46, '213', '阿爾及利亞', '阿尔及利亚', 'DZ', 'Algeria', '-8', 1, 1, 'アルジェリア');
INSERT INTO `region` VALUES (47, '376', '安道爾共和國', '安道尔共和国', 'AD', 'Andorra', '-8', 1, 1, 'アンドラ共和国');
INSERT INTO `region` VALUES (48, '1264', '安圭拉島', '安圭拉岛', 'AI', 'Anguilla', '-12', 1, 1, 'アンギラ島');
INSERT INTO `region` VALUES (49, '1268', '安提瓜和巴布達', '安提瓜和巴布达', 'AG', 'Antigua and Barbuda', '-12', 1, 1, 'アンティグア・バーブーダ');
INSERT INTO `region` VALUES (50, '54', '阿根廷', '阿根廷', 'AR', 'Argentina', '-11', 1, 1, 'アルゼンチン');
INSERT INTO `region` VALUES (51, '374', '亞美尼亞', '亚美尼亚', 'AM', 'Armenia', '-6', 1, 1, 'アルメニア');
INSERT INTO `region` VALUES (52, '247', '阿森松', '阿森松', 'AC', 'Ascension', '-8', 1, 1, 'アセンション島');
INSERT INTO `region` VALUES (53, '61', '澳大利亞', '澳大利亚', 'AU', 'Australia', '+2', 1, 1, 'オーストラリア');
INSERT INTO `region` VALUES (54, '43', '奧地利', '奥地利', 'AT', 'Austria', '-7', 1, 1, 'オーストリア');
INSERT INTO `region` VALUES (55, '994', '阿塞拜疆', '阿塞拜疆', 'AZ', 'Azerbaijan', '-5', 1, 1, 'アゼルバイジャン');
INSERT INTO `region` VALUES (56, '1242', '巴哈馬', '巴哈马', 'BS', 'Bahamas', '-13', 1, 1, 'バハマ');
INSERT INTO `region` VALUES (57, '973', '巴林', '巴林', 'BH', 'Bahrain', '-5', 1, 1, 'バーレーン');
INSERT INTO `region` VALUES (58, '880', '孟加拉國', '孟加拉国', 'BD', 'Bangladesh', '-2', 1, 1, 'バングラデシュ');
INSERT INTO `region` VALUES (59, '1246', '巴巴多斯', '巴巴多斯', 'BB', 'Barbados', '-12', 1, 1, 'バルバドス');
INSERT INTO `region` VALUES (60, '375', '白俄羅斯', '白俄罗斯', 'BY', 'Belarus', '-6', 1, 1, 'ベラルーシ');
INSERT INTO `region` VALUES (61, '32', '比利時', '比利时', 'BE', 'Belgium', '-7', 1, 1, 'ベルギー');
INSERT INTO `region` VALUES (62, '501', '伯利茲', '伯利兹', 'BZ', 'Belize', '-14', 1, 1, 'ベリーズ');
INSERT INTO `region` VALUES (63, '229', '貝寧', '贝宁', 'BJ', 'Benin', '-7', 1, 1, 'ベナン');
INSERT INTO `region` VALUES (64, '1441', '百慕達群島', '百慕大群岛', 'BM', 'Bermuda Is.', '-12', 1, 1, 'バミューダ諸島');
INSERT INTO `region` VALUES (65, '591', '玻利維亞', '玻利维亚', 'BO', 'Bolivia', '-12', 1, 1, 'ボリビア');
INSERT INTO `region` VALUES (66, '267', '博茨瓦納', '博茨瓦纳', 'BW', 'Botswana', '-6', 1, 1, 'ボツワナ');
INSERT INTO `region` VALUES (67, '55', '巴西', '巴西', 'BR', 'Brazil', '-11', 1, 1, 'ブラジル');
INSERT INTO `region` VALUES (68, '673', '文萊', '文莱', 'BN', 'Brunei', '0', 1, 1, 'ブルネイ');
INSERT INTO `region` VALUES (69, '359', '保加利亞', '保加利亚', 'BG', 'Bulgaria', '-6', 1, 1, 'ブルガリア');
INSERT INTO `region` VALUES (70, '226', '布基納法索', '布基纳法索', 'BF', 'Burkina-faso', '-8', 1, 1, 'ブルキナファソ');
INSERT INTO `region` VALUES (71, '95', '緬甸', '缅甸', 'MM', 'Burma', '-1.3', 1, 1, 'ミャンマー');
INSERT INTO `region` VALUES (72, '257', '布隆迪', '布隆迪', 'BI', 'Burundi', '-6', 1, 1, 'ブルンジ');
INSERT INTO `region` VALUES (73, '237', '喀麥隆', '喀麦隆', 'CM', 'Cameroon', '-7', 1, 1, 'カメルーン');
INSERT INTO `region` VALUES (74, '1', '加拿大', '加拿大', 'CA', 'Canada', '-13', 1, 1, 'カナダ');
INSERT INTO `region` VALUES (75, '1345', '開曼群島', '开曼群岛', 'KY', 'Cayman Is.', '-13', 1, 1, 'ケイマン諸島');
INSERT INTO `region` VALUES (76, '236', '中非共和國', '中非共和国', 'CF', 'Central African Republic', '-7', 1, 1, '中央アフリカ共和国');
INSERT INTO `region` VALUES (77, '235', '乍得', '乍得', 'TD', 'Chad', '-7', 1, 1, 'チャド');
INSERT INTO `region` VALUES (78, '56', '智利', '智利', 'CL', 'Chile', '-13', 1, 1, 'チリ');
INSERT INTO `region` VALUES (79, '86', '中國', '中国', 'CN', 'China', '0', 1, 1, '中国');
INSERT INTO `region` VALUES (80, '57', '哥倫比亞', '哥伦比亚', 'CO', 'Colombia', '0', 1, 1, 'コロンビア');
INSERT INTO `region` VALUES (81, '242', '剛果(布)', '刚果', 'CG', 'Congo', '-7', 1, 1, 'コンゴ');
INSERT INTO `region` VALUES (82, '682', '庫克群島', '库克群岛', 'CK', 'Cook Is.', '-18.3', 1, 1, 'クック諸島');
INSERT INTO `region` VALUES (83, '506', '哥斯達黎加', '哥斯达黎加', 'CR', 'Costa Rica', '-14', 1, 1, 'コスタリカ');
INSERT INTO `region` VALUES (84, '53', '古巴', '古巴', 'CU', 'Cuba', '-13', 1, 1, 'キューバ');
INSERT INTO `region` VALUES (85, '357', '塞浦路斯', '塞浦路斯', 'CY', 'Cyprus', '-6', 1, 1, 'キプロス');
INSERT INTO `region` VALUES (86, '420', '捷克', '捷克', 'CZ', 'Czech', '-7', 1, 1, 'チェコ');
INSERT INTO `region` VALUES (87, '45', '丹麥', '丹麦', 'DK', 'Denmark', '-7', 1, 1, 'デンマーク');
INSERT INTO `region` VALUES (88, '253', '吉布堤', '吉布提', 'DJ', 'Djibouti', '-5', 1, 1, 'ジブチ');
INSERT INTO `region` VALUES (89, '1890', '多明尼加共和國共和國', '多米尼加共和国', 'DO', 'Dominica Rep.', '-13', 1, 1, 'ドミニカ共和国');
INSERT INTO `region` VALUES (90, '593', '厄瓜多爾', '厄瓜多尔', 'EC', 'Ecuador', '-13', 1, 1, 'エクアドル');
INSERT INTO `region` VALUES (91, '20', '埃及', '埃及', 'EG', 'Egypt', '-6', 1, 1, 'エジプト');
INSERT INTO `region` VALUES (92, '503', '薩爾瓦多', '萨尔瓦多', 'SV', 'EI Salvador', '-14', 1, 1, 'エルサルバドル');
INSERT INTO `region` VALUES (93, '372', '愛沙尼亞', '爱沙尼亚', 'EE', 'Estonia', '-5', 1, 1, 'エストニア');
INSERT INTO `region` VALUES (94, '251', '埃塞俄比亞', '埃塞俄比亚', 'ET', 'Ethiopia', '-5', 1, 1, 'エチオピア');
INSERT INTO `region` VALUES (95, '679', '斐濟', '斐济', 'FJ', 'Fiji', '+4', 1, 1, 'フィジー');
INSERT INTO `region` VALUES (96, '358', '芬蘭', '芬兰', 'FI', 'Finland', '-6', 1, 1, 'フィンランド');
INSERT INTO `region` VALUES (97, '33', '法國', '法国', 'FR', 'France', '-8', 1, 1, 'フランス');
INSERT INTO `region` VALUES (98, '594', '法屬圭亞那', '法属圭亚那', 'GF', 'French Guiana', '-12', 1, 1, 'フランス領ギアナ');
INSERT INTO `region` VALUES (99, '241', '加蓬', '加蓬', 'GA', 'Gabon', '-7', 1, 1, 'ガボン');
INSERT INTO `region` VALUES (100, '220', '岡比亞', '冈比亚', 'GM', 'Gambia', '-8', 1, 1, 'ガンビア');
INSERT INTO `region` VALUES (101, '995', '格魯吉亞', '格鲁吉亚', 'GE', 'Georgia', '0', 1, 1, 'グルジア');
INSERT INTO `region` VALUES (102, '49', '德國', '德国', 'DE', 'Germany', '-7', 1, 1, 'ドイツ');
INSERT INTO `region` VALUES (103, '233', '加納', '加纳', 'GH', 'Ghana', '-8', 1, 1, 'ガーナ');
INSERT INTO `region` VALUES (104, '350', '直布羅陀', '直布罗陀', 'GI', 'Gibraltar', '-8', 1, 1, 'ジブラルタル');
INSERT INTO `region` VALUES (105, '30', '希臘', '希腊', 'GR', 'Greece', '-6', 1, 1, 'ギリシャ');
INSERT INTO `region` VALUES (106, '1809', '格林納達', '格林纳达', 'GD', 'Grenada', '-14', 1, 1, 'グレナダ');
INSERT INTO `region` VALUES (107, '1671', '關島', '关岛', 'GU', 'Guam', '+2', 1, 1, 'グアム');
INSERT INTO `region` VALUES (108, '502', '危地馬拉', '危地马拉', 'GT', 'Guatemala', '-14', 1, 1, 'グアテマラ');
INSERT INTO `region` VALUES (109, '224', '幾內亞', '几内亚', 'GN', 'Guinea', '-8', 1, 1, 'ギニア');
INSERT INTO `region` VALUES (110, '592', '圭亞那', '圭亚那', 'GY', 'Guyana', '-11', 1, 1, 'ガイアナ');
INSERT INTO `region` VALUES (111, '509', '海地', '海地', 'HT', 'Haiti', '-13', 1, 1, 'ハイチ');
INSERT INTO `region` VALUES (112, '504', '洪都拉斯', '洪都拉斯', 'HN', 'Honduras', '-14', 1, 1, 'ホンジュラス');
INSERT INTO `region` VALUES (113, '852', '中國香港', '香港', 'HK', 'Hongkong', '0', 1, 1, '香港');
INSERT INTO `region` VALUES (114, '36', '匈牙利', '匈牙利', 'HU', 'Hungary', '-7', 1, 1, 'ハンガリー');
INSERT INTO `region` VALUES (115, '354', '冰島', '冰岛', 'IS', 'Iceland', '-9', 1, 1, 'アイスランド');
INSERT INTO `region` VALUES (116, '91', '印度', '印度', 'IN', 'India', '-2.3', 1, 1, 'インド');
INSERT INTO `region` VALUES (117, '62', '印度尼西亞', '印度尼西亚', 'ID', 'Indonesia', '-0.3', 1, 1, 'インドネシア');
INSERT INTO `region` VALUES (118, '98', '伊朗', '伊朗', 'IR', 'Iran', '-4.3', 1, 1, 'イラン');
INSERT INTO `region` VALUES (119, '964', '伊拉克', '伊拉克', 'IQ', 'Iraq', '-5', 1, 1, 'イラク');
INSERT INTO `region` VALUES (120, '353', '愛爾蘭', '爱尔兰', 'IE', 'Ireland', '-4.3', 1, 1, 'アイルランド');
INSERT INTO `region` VALUES (121, '972', '以色列', '以色列', 'IL', 'Israel', '-6', 1, 1, 'イスラエル');
INSERT INTO `region` VALUES (122, '39', '意大利', '意大利', 'IT', 'Italy', '-7', 1, 1, 'イタリア');
INSERT INTO `region` VALUES (123, '225', '科特迪瓦', '科特迪瓦', 'KT', 'Ivory Coast', '-6', 1, 1, 'コートジボワール');
INSERT INTO `region` VALUES (124, '1876', '牙買加', '牙买加', 'JM', 'Jamaica', '-12', 1, 1, 'ジャマイカ');
INSERT INTO `region` VALUES (125, '81', '日本', '日本', 'JP', 'Japan', '+1', 1, 1, '日本');
INSERT INTO `region` VALUES (126, '962', '約旦', '约旦', 'JO', 'Jordan', '-6', 1, 1, 'ヨルダン');
INSERT INTO `region` VALUES (127, '855', '柬埔寨', '柬埔寨', 'KH', 'Kampuchea （Cambodia）', '-1', 1, 1, 'カンボジア');
INSERT INTO `region` VALUES (128, '327', '哈薩克', '哈萨克斯坦', 'KZ', 'Kazakstan', '-5', 1, 1, 'カザフスタン');
INSERT INTO `region` VALUES (129, '254', '肯雅', '肯尼亚', 'KE', 'Kenya', '-5', 1, 1, 'ケニア');
INSERT INTO `region` VALUES (130, '82', '韓國', '韩国', 'KR', 'Korea', '+1', 1, 1, '韓国');
INSERT INTO `region` VALUES (131, '965', '科威特', '科威特', 'KW', 'Kuwait', '-5', 1, 1, 'クウェート');
INSERT INTO `region` VALUES (132, '331', '吉爾吉斯坦', '吉尔吉斯坦', 'KG', 'Kyrgyzstan', '-5', 1, 1, 'キルギスタン');
INSERT INTO `region` VALUES (133, '856', '寮國', '老挝', 'LA', 'Laos', '-1', 1, 1, 'ラオス');
INSERT INTO `region` VALUES (134, '371', '拉脫維亞', '拉脱维亚', 'LV', 'Latvia', '-5', 1, 1, 'ラトビア');
INSERT INTO `region` VALUES (135, '961', '黎巴嫩', '黎巴嫩', 'LB', 'Lebanon', '-6', 1, 1, 'レバノン');
INSERT INTO `region` VALUES (136, '266', '萊索托', '莱索托', 'LS', 'Lesotho', '-6', 1, 1, 'レソト');
INSERT INTO `region` VALUES (137, '231', '利比里亞', '利比里亚', 'LR', 'Liberia', '-8', 1, 1, 'リベリア');
INSERT INTO `region` VALUES (138, '218', '利比亞', '利比亚', 'LY', 'Libya', '-6', 1, 1, 'リビア');
INSERT INTO `region` VALUES (139, '423', '列支敦士登', '列支敦士登', 'LI', 'Liechtenstein', '-7', 1, 1, 'リヒテンシュタイン');
INSERT INTO `region` VALUES (140, '370', '立陶宛', '立陶宛', 'LT', 'Lithuania', '-5', 1, 1, 'リトアニア');
INSERT INTO `region` VALUES (141, '352', '盧森堡', '卢森堡', 'LU', 'Luxembourg', '-7', 1, 1, 'ルクセンブルク');
INSERT INTO `region` VALUES (142, '853', '中國澳門', '澳门', 'MO', 'Macao', '0', 1, 1, 'マカオ');
INSERT INTO `region` VALUES (143, '261', '馬達加斯加', '马达加斯加', 'MG', 'Madagascar', '-5', 1, 1, 'マダガスカル');
INSERT INTO `region` VALUES (144, '265', '馬拉維', '马拉维', 'MW', 'Malawi', '-6', 1, 1, 'マラウイ');
INSERT INTO `region` VALUES (145, '60', '馬來西亞', '马来西亚', 'MY', 'Malaysia', '-0.5', 1, 1, 'マレーシア');
INSERT INTO `region` VALUES (146, '960', '馬爾代夫', '马尔代夫', 'MV', 'Maldives', '-7', 1, 1, 'モルディブ');
INSERT INTO `region` VALUES (147, '223', '馬里', '马里', 'ML', 'Mali', '-8', 1, 1, 'マリ');
INSERT INTO `region` VALUES (148, '356', '馬爾他', '马耳他', 'MT', 'Malta', '-7', 1, 1, 'マルタ');
INSERT INTO `region` VALUES (149, '1670', '馬里亞那群島', '马里亚纳群岛', 'MP', 'Mariana Is.', '+1', 1, 1, 'マリアナ諸島');
INSERT INTO `region` VALUES (150, '596', '馬提尼克島', '马提尼克', 'MQ', 'Martinique', '-12', 1, 1, 'マルティニーク');
INSERT INTO `region` VALUES (151, '230', '毛里裘斯', '毛里求斯', 'MU', 'Mauritius', '-4', 1, 1, 'モーリシャス');
INSERT INTO `region` VALUES (152, '52', '墨西哥', '墨西哥', 'MX', 'Mexico', '-15', 1, 1, 'メキシコ');
INSERT INTO `region` VALUES (153, '373', '摩爾多瓦', '摩尔多瓦', 'MD', 'Moldova', '-5', 1, 1, 'モルドバ');
INSERT INTO `region` VALUES (154, '377', '摩納哥', '摩纳哥', 'MC', 'Monaco', '-7', 1, 1, 'モナコ');
INSERT INTO `region` VALUES (155, '976', '蒙古', '蒙古', 'MN', 'Mongolia', '0', 1, 1, 'モンゴル');
INSERT INTO `region` VALUES (156, '1664', '蒙特塞拉特島', '蒙特塞拉特岛', 'MS', 'Montserrat Is.', '-12', 1, 1, 'モンテセルラト島');
INSERT INTO `region` VALUES (157, '212', '摩洛哥', '摩洛哥', 'MA', 'Morocco', '-6', 1, 1, 'モロッコ');
INSERT INTO `region` VALUES (158, '258', '莫桑比克', '莫桑比克', 'MZ', 'Mozambique', '-6', 1, 1, 'モザンビーク');
INSERT INTO `region` VALUES (159, '264', '納米比亞', '纳米比亚', 'NA', 'Namibia', '-7', 1, 1, 'ナミビア');
INSERT INTO `region` VALUES (160, '674', '瑙魯', '瑙鲁', 'NR', 'Nauru', '+4', 1, 1, 'ナウル');
INSERT INTO `region` VALUES (161, '977', '尼泊爾', '尼泊尔', 'NP', 'Nepal', '-2.3', 1, 1, 'ネパール');
INSERT INTO `region` VALUES (162, '599', '荷屬安地列斯', '荷属安的列斯', 'AN', 'Netheriands Antilles', '-12', 1, 1, 'オランダ領アンティル');
INSERT INTO `region` VALUES (163, '31', '荷蘭', '荷兰', 'NL', 'Netherlands', '-7', 1, 1, 'オランダ');
INSERT INTO `region` VALUES (164, '64', '新西蘭', '新西兰', 'NZ', 'New Zealand', '+4', 1, 1, 'ニュージーランド');
INSERT INTO `region` VALUES (165, '505', '尼加拉瓜', '尼加拉瓜', 'NI', 'Nicaragua', '-14', 1, 1, 'ニカラグア');
INSERT INTO `region` VALUES (166, '227', '尼日爾', '尼日尔', 'NE', 'Niger', '-8', 1, 1, 'ニジェール');
INSERT INTO `region` VALUES (167, '234', '尼日利亞', '尼日利亚', 'NG', 'Nigeria', '-7', 1, 1, 'ナイジェリア');
INSERT INTO `region` VALUES (168, '850', '朝鮮', '朝鲜', 'KP', 'North Korea', '+1', 1, 1, '北朝鮮');
INSERT INTO `region` VALUES (169, '47', '挪威', '挪威', 'NO', 'Norway', '-7', 1, 1, 'ノルウェー');
INSERT INTO `region` VALUES (170, '968', '阿曼', '阿曼', 'OM', 'Oman', '-4', 1, 1, 'オマーン');
INSERT INTO `region` VALUES (171, '92', '巴基斯坦', '巴基斯坦', 'PK', 'Pakistan', '-2.3', 1, 1, 'パキスタン');
INSERT INTO `region` VALUES (172, '507', '巴拿馬', '巴拿马', 'PA', 'Panama', '-13', 1, 1, 'パナマ');
INSERT INTO `region` VALUES (173, '675', '巴布亞新畿內亞', '巴布亚新几内亚', 'PG', 'Papua New Cuinea', '+2', 1, 1, 'パプアニューギニア');
INSERT INTO `region` VALUES (174, '595', '巴拉圭', '巴拉圭', 'PY', 'Paraguay', '-12', 1, 1, 'パラグアイ');
INSERT INTO `region` VALUES (175, '51', '秘魯', '秘鲁', 'PE', 'Peru', '-13', 1, 1, 'ペルー');
INSERT INTO `region` VALUES (176, '63', '菲律賓', '菲律宾', 'PH', 'Philippines', '0', 1, 1, 'フィリピン');
INSERT INTO `region` VALUES (177, '48', '波蘭', '波兰', 'PL', 'Poland', '-7', 1, 1, 'ポーランド');
INSERT INTO `region` VALUES (178, '689', '法屬玻利尼西亞', '法属玻利尼西亚', 'PF', 'French Polynesia', '+3', 1, 1, 'フランス領ポリネシア');
INSERT INTO `region` VALUES (179, '351', '葡萄牙', '葡萄牙', 'PT', 'Portugal', '-8', 1, 1, 'ポルトガル');
INSERT INTO `region` VALUES (180, '1787', '波多黎各', '波多黎各', 'PR', 'Puerto Rico', '-12', 1, 1, 'プエルトリコ');
INSERT INTO `region` VALUES (181, '974', '卡塔爾', '卡塔尔', 'QA', 'Qatar', '-5', 1, 1, 'カタール');
INSERT INTO `region` VALUES (182, '262', '留尼旺', '留尼旺', 'RE', 'Reunion', '-4', 1, 1, 'レユニオン');
INSERT INTO `region` VALUES (183, '40', '羅馬尼亞', '罗马尼亚', 'RO', 'Romania', '-6', 1, 1, 'ルーマニア');
INSERT INTO `region` VALUES (184, '7', '俄羅斯', '俄罗斯', 'RU', 'Russia', '-5', 1, 1, 'ロシア');
INSERT INTO `region` VALUES (185, '1758', '聖盧西亞', '圣卢西亚', 'LC', 'Saint Lueia', '-12', 1, 1, 'セントルシア');
INSERT INTO `region` VALUES (186, '1784', '聖文森特島', '圣文森特岛', 'VC', 'Saint Vincent', '-12', 1, 1, 'セント・ヴィンセント島');
INSERT INTO `region` VALUES (187, '684', '東薩摩亞(美)', '东萨摩亚（美）', 'AS', 'Samoa Eastern', '-19', 1, 1, 'アメリカ領サモア');
INSERT INTO `region` VALUES (188, '685', '西薩摩亞', '西萨摩亚', 'WS', 'Samoa Western', '-19', 1, 1, 'サイサモア');
INSERT INTO `region` VALUES (189, '378', '聖馬力諾', '圣马力诺', 'SM', 'San Marino', '-7', 1, 1, 'サンマリノ');
INSERT INTO `region` VALUES (190, '239', '聖多美和普林西比', '圣多美和普林西比', 'ST', 'Sao Tome and Principe', '-8', 1, 1, 'サントメ・プリンシペ');
INSERT INTO `region` VALUES (191, '966', '沙地阿拉伯', '沙特阿拉伯', 'SA', 'Saudi Arabia', '-5', 1, 1, 'サウジアラビア');
INSERT INTO `region` VALUES (192, '221', '塞內加爾', '塞内加尔', 'SN', 'Senegal', '-8', 1, 1, 'セネガル');
INSERT INTO `region` VALUES (193, '248', '塞舌爾', '塞舌尔', 'SC', 'Seychelles', '-4', 1, 1, 'セーシェル');
INSERT INTO `region` VALUES (194, '232', '塞拉利昂', '塞拉利昂', 'SL', 'Sierra Leone', '-8', 1, 1, 'シエラレオネ');
INSERT INTO `region` VALUES (195, '65', '新加坡', '新加坡', 'SG', 'Singapore', '+0.3', 1, 1, 'シンガポール');
INSERT INTO `region` VALUES (196, '421', '斯洛伐克', '斯洛伐克', 'SK', 'Slovakia', '-7', 1, 1, 'スロバキア');
INSERT INTO `region` VALUES (197, '386', '斯洛文尼亞', '斯洛文尼亚', 'SI', 'Slovenia', '-7', 1, 1, 'スロベニア');
INSERT INTO `region` VALUES (198, '677', '所羅門群島', '所罗门群岛', 'SB', 'Solomon Is.', '+3', 1, 1, 'ソロモン諸島');
INSERT INTO `region` VALUES (199, '252', '索馬里', '索马里', 'SO', 'Somali', '-5', 1, 1, 'ソマリア');
INSERT INTO `region` VALUES (200, '27', '南非', '南非', 'ZA', 'South Africa', '-6', 1, 1, '南アフリカ共和国');
INSERT INTO `region` VALUES (201, '34', '西班牙', '西班牙', 'ES', 'Spain', '-8', 1, 1, 'スペイン');
INSERT INTO `region` VALUES (202, '94', '斯裡蘭卡', '斯里兰卡', 'LK', 'Sri Lanka', '0', 1, 1, 'スリランカ');
INSERT INTO `region` VALUES (203, '249', '蘇丹', '苏丹', 'SD', 'Sudan', '-6', 1, 1, 'スーダン');
INSERT INTO `region` VALUES (204, '211', '南蘇丹', '南苏丹', 'SS', 'South Sudan', '-6', 1, 1, '南スーダン共和国');
INSERT INTO `region` VALUES (205, '597', '蘇里南', '苏里南', 'SR', 'Suriname', '-11.3', 1, 1, 'スリナム');
INSERT INTO `region` VALUES (206, '268', '斯威士蘭', '斯威士兰', 'SZ', 'Swaziland', '-6', 1, 1, 'スワジランド');
INSERT INTO `region` VALUES (207, '46', '瑞典', '瑞典', 'SE', 'Sweden', '-7', 1, 1, 'スウェーデン');
INSERT INTO `region` VALUES (208, '41', '瑞士', '瑞士', 'CH', 'Switzerland', '-7', 1, 1, 'スイス');
INSERT INTO `region` VALUES (209, '963', '敘利亞', '叙利亚', 'SY', 'Syria', '-6', 1, 1, 'シリア');
INSERT INTO `region` VALUES (210, '886', '中國台灣', '台湾省', 'TW', 'Taiwan', '0', 1, 1, '台湾省');
INSERT INTO `region` VALUES (211, '992', '塔吉克', '塔吉克斯坦', 'TJ', 'Tajikstan', '-5', 1, 1, 'タジキスタン');
INSERT INTO `region` VALUES (212, '255', '坦桑尼亞', '坦桑尼亚', 'TZ', 'Tanzania', '-5', 1, 1, 'タンザニア');
INSERT INTO `region` VALUES (213, '66', '泰國', '泰国', 'TH', 'Thailand', '-1', 1, 1, 'タイ');
INSERT INTO `region` VALUES (214, '228', '多哥', '多哥', 'TG', 'Togo', '-8', 1, 1, 'トーゴ');
INSERT INTO `region` VALUES (215, '676', '湯加', '汤加', 'TO', 'Tonga', '+4', 1, 1, 'トンガ');
INSERT INTO `region` VALUES (216, '1809', '特立尼達和多巴哥', '特立尼达和多巴哥', 'TT', 'Trinidad and Tobago', '-12', 1, 1, 'トリニダード・トバゴ');
INSERT INTO `region` VALUES (217, '216', '突尼斯', '突尼斯', 'TN', 'Tunisia', '-7', 1, 1, 'チュニジア');
INSERT INTO `region` VALUES (218, '90', '土耳其', '土耳其', 'TR', 'Turkey', '-6', 1, 1, 'トルコ');
INSERT INTO `region` VALUES (219, '993', '土庫曼', '土库曼斯坦', 'TM', 'Turkmenistan', '-5', 1, 1, 'トルクメニスタン');
INSERT INTO `region` VALUES (220, '256', '烏幹達', '乌干达', 'UG', 'Uganda', '-5', 1, 1, 'ウガンダ');
INSERT INTO `region` VALUES (221, '380', '烏克蘭', '乌克兰', 'UA', 'Ukraine', '-5', 1, 1, 'ウクライナ');
INSERT INTO `region` VALUES (222, '971', '阿拉伯聯合酋長國', '阿拉伯联合酋长国', 'AE', 'United Arab Emirates', '-4', 1, 1, 'アラブ首長国連邦');
INSERT INTO `region` VALUES (223, '44', '英國', '英国', 'GB', 'United Kiongdom', '-8', 1, 1, 'イギリス');
INSERT INTO `region` VALUES (224, '1', '美國', '美国', 'US', 'United States of America', '-13', 1, 1, 'アメリカ');
INSERT INTO `region` VALUES (225, '598', '烏拉圭', '乌拉圭', 'UY', 'Uruguay', '-10.3', 1, 1, 'ウルグアイ');
INSERT INTO `region` VALUES (226, '233', '烏茲別克', '乌兹别克斯坦', 'UZ', 'Uzbekistan', '-5', 1, 1, 'ウズベキスタン');
INSERT INTO `region` VALUES (227, '58', '委內瑞拉', '委内瑞拉', 'VE', 'Venezuela', '-12.3', 1, 1, 'ベネズエラ');
INSERT INTO `region` VALUES (228, '84', '越南', '越南', 'VN', 'Vietnam', '-1', 1, 1, 'ベトナム');
INSERT INTO `region` VALUES (229, '967', '也門', '也门', 'YE', 'Yemen', '-5', 1, 1, 'イエメン');
INSERT INTO `region` VALUES (230, '381', '南斯拉夫', '南斯拉夫', 'YU', 'Yugoslavia', '-7', 1, 1, 'ユーゴスラビア');
INSERT INTO `region` VALUES (231, '263', '津巴布韋', '津巴布韦', 'ZW', 'Zimbabwe', '-6', 1, 1, 'ジンバブエ');
INSERT INTO `region` VALUES (232, '243', '剛果民主共和國共和國(金)', '刚果民主共和国(金)', 'CD', 'Congo-kinshasa', '-7', 1, 1, 'コンゴ民主共和国');
INSERT INTO `region` VALUES (233, '260', '贊比亞', '赞比亚', 'ZM', 'Zambia', '-6', 1, 1, 'ザンビア');
